version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql/mysql-server
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

volumes:
  db-data:
    