version: '3'
services:

  mysql:
    container_name: mysql
    image: mysql/mysql-server
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "topic1:1:1,topic2:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  testapp:
    container_name: testapp
    image: testapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    environment:
      APP_NAME: ledger
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: admin
      DB_PWD: admin
      LIQUIBASE_CHANGELOG: db/changelog/db.changelog-master.yml
      TOPIC1: topic1
      TOPIC2: topic2
      BOOTSTRAP_SERVER: kafka:9092

volumes:
  db-data:

    